# Generated by Django 6.0.2 on 2026-02-09 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_locked', models.BooleanField(default=False)),
                ('students', models.ManyToManyField(related_name='subthemes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('max_length', models.IntegerField()),
                ('order', models.IntegerField()),
                ('subtheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.subtheme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
