# Generated by Django 6.0.2 on 2026-02-09 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('quote', 'Citation')], max_length=10)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.section')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('book', 'Livre'), ('article', 'Article'), ('website', 'Site web'), ('interview', 'Interview'), ('archive', 'Archive')], max_length=10)),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True)),
                ('year', models.CharField(max_length=10)),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='content.contentblock')),
            ],
        ),
    ]
